//------------------------------------------<< Generated source >>-------------------------------------------//
//-----------------------------------------------[ Modules ]-------------------------------------------------//
//----------------------------------------------------*------------------------------------------------------//
//----[                                                                                                 ]----//
//----[         |||||             |||||                       ||||||||||       ||||||||||               ]----//
//----[        ||| |||           ||| |||                      |||     ||||     |||     ||||             ]----//
//----[       |||   |||         |||   |||                     |||       |||    |||       |||            ]----//
//----[       ||     ||         ||     ||                     |||       |||    |||       |||            ]----//
//----[      |||     |||       |||     |||                    |||     ||||     |||     ||||             ]----//
//----[      ||       ||       ||       ||     __________     ||||||||||       ||||||||||               ]----//
//----[     |||       |||     |||       |||                   |||    |||       |||                      ]----//
//----[     ||         ||     ||         ||                   |||     ||       |||                      ]----//
//----[    |||         |||   |||         |||                  |||     |||      |||                      ]----//
//----[    ||           ||   ||           ||                  |||      ||      |||                      ]----//
//----[   |||           ||| |||           |||                 |||      |||     |||                      ]----//
//----[  |||             |||||             |||                |||       |||    |||                      ]----//
//----[                                                                                                 ]----//
//----------------------------------------------------*------------------------------------------------------//
// Kod wygenerowany automatycznie narz�dziem Mrucznik CTL

// ================= UWAGA! =================
//
// WSZELKIE ZMIANY WPROWADZONE DO TEGO PLIKU
// ZOSTAN¥ NADPISANE PO WYWO£ANIU KOMENDY
// > mrucznikctl build
//
// ================= UWAGA! =================

#include <YSI_Storage\y_ini>


//-------<[ .def ]>-------
#include "grupy/grupy.def"
#include "gunshop/gunshop.def"
#include "bilboard\bilboard.def"
#include "szmugler/szmugler.def"
//#include "eventy/eventy.def"
#include "deskorolka/deskorolka.def"
#include "Nicki3D/Nicki3D.def"
//#include "zmeczenie/zmeczenie.def"
#include "sweeper/sweeper.def"
#include "fps/fps.def"
#include "magazynier/magazynier.def"
#include "tatuaz/tatuaz.def"
#include "03DL\03DL.def"
#include "actors\actors.def"
#include "admin\admin.def"
#include "adminduty\adminduty.def"
#include "animacje\animacje.def"
#include "antycheat\antycheat.def"
#include "antyspam\antyspam.def"
#include "biznesy\biznesy.def"
#include "bramy\bramy.def"
#include "bronie\bronie.def"
#include "budki\budki.def"
#include "bw\bw.def"
#include "chaty\chaty.def"
#include "choroby\choroby.def"
#include "convoy\convoy.def"
#include "cooking\cooking.def"
#include "debug\debug.def"
#include "discord\discord.def"
#include "fishing\fishing.def"
#include "frakcje\frakcje.def"
#include "glod\glod.def"
#include "gps\gps.def"
#include "graffiti\graffiti.def"
#include "ibiza\ibiza.def"
#include "komendy\komendy.def"
#include "logi\logi.def"
#include "money\money.def"
#include "motele\motele.def"
#include "names\names.def"
#include "napady\napady.def"
#include "oferty\oferty.def"
#include "organizacje\organizacje.def"
#include "pizzaman\pizzaman.def"
#include "player_attachments\player_attachments.def"
#include "pojazdy\pojazdy.def"
#include "prace\prace.def"
#include "premium\premium.def"
#include "produkty\produkty.def"
#include "wejscia\wejscia.def"
#include "antycheat\antycheat.def"
#include "chaty\chaty.def"
#include "ibiza\ibiza.def"
#include "system-obiekty\system-obiekty.def"
#include "system-kary\system-kary.def"
#include "systemcial\systemcial.def"
#include "przedmioty\przedmioty.def"
#include "sannews\sannews.def" 
#include "sila\sila.def"
#include "strzelnica\strzelnica.def"
#include "sklep\sklep.def" 
#include "urzadls\urzadls.def"
#include "vehicle_attachments\vehicle_attachments.def"
#include "wejscia\wejscia.def"
#include "wypadek\wypadek.def"
#include "tune\tune.def"


//-------<[ .hwn ]>-------
#include "grupy/grupy.hwn"
#include "gunshop/gunshop.hwn"
#include "bilboard\bilboard.hwn"
#include "szmugler/szmugler.hwn"
#include "tatuaz/tatuaz.hwn"
//#include "eventy/eventy.hwn"
#include "deskorolka/deskorolka.hwn"
#include "Nicki3D/Nicki3D.hwn"
#include "sweeper/sweeper.hwn"
#include "fps/fps.hwn"
#include "magazynier/magazynier.hwn"
#include "03DL\03DL.hwn"
#include "actors\actors.hwn"
#include "admin\admin.hwn"
#include "adminduty\adminduty.hwn"
#include "animacje\animacje.hwn"
#include "antycheat\antycheat.hwn"
#include "antyspam\antyspam.hwn"
#include "biznesy\biznesy.hwn"
#include "bramy\bramy.hwn"
#include "bronie\bronie.hwn"
#include "budki\budki.hwn"
#include "bw\bw.hwn"
#include "chaty\chaty.hwn"
#include "choroby\choroby.hwn"
#include "convoy\convoy.hwn"
#include "cooking\cooking.hwn"
#include "debug\debug.hwn"
#include "discord\discord.hwn"
#include "fishing\fishing.hwn"
#include "frakcje\frakcje.hwn"
#include "glod\glod.hwn"
#include "gps\gps.hwn"
#include "graffiti\graffiti.hwn"
#include "ibiza\ibiza.hwn"
#include "komendy\komendy.hwn"
#include "logi\logi.hwn"
#include "money\money.hwn"
#include "motele\motele.hwn"
//#include "mrpac\mrpac.hwn"
#include "names\names.hwn"
#include "napady\napady.hwn"
#include "oferty\oferty.hwn"
#include "organizacje\organizacje.hwn"
#include "pizzaman\pizzaman.hwn"
#include "player_attachments\player_attachments.hwn"
#include "pojazdy\pojazdy.hwn"
#include "prace\prace.hwn"
#include "premium\premium.hwn"
#include "produkty\produkty.hwn"
#include "przedmioty\przedmioty.hwn"
#include "sannews\sannews.hwn"
#include "sila\sila.hwn"
#include "strzelnica\strzelnica.hwn"
#include "sklep\sklep.hwn"
#include "system-obiekty\system-obiekty.hwn"
#include "system-kary\system-kary.hwn"
#include "systemcial\systemcial.hwn"
#include "urzadls\urzadls.hwn"
#include "vehicle_attachments\vehicle_attachments.hwn"
#include "wejscia\wejscia.hwn"
#include "wypadek\wypadek.hwn"
#include "antycheat\antycheat.hwn"
#include "chaty\chaty.hwn"
#include "ibiza\ibiza.hwn"
#include "system-obiekty\system-obiekty.hwn"
#include "napady\napady.hwn"
#include "tune\tune.hwn"


//-------<[ .pwn ]>-------
#include "protekcja/protekcja.pwn"
#include "strefy/strefy.pwn"
#include "grupy/grupy.pwn"
#include "protekcja/protekcja.pwn"
#include "strefy/strefy.pwn"
//#include misje/misje.pwn
#include "silownia/silownia.pwn"
//#include "airdropy/airdrop.pwn"
#include "gazeciarz/gazeciarz.pwn"
#include "gunshop/gunshop.pwn"
#include "bilboard\bilboard.pwn"
#include "tatuaz/tatuaz.pwn"
#include "exp/exp.pwn"
#include "osiagniecia/osiagniecia.pwn"
#include "reczny/reczny.pwn"
#include "szmugler/szmugler.pwn"
//#include "eventy/eventy.pwn"
#include "deskorolka/deskorolka.pwn"
#include "system_narko/system_narko.pwn"
#include "Nicki3D/Nicki3D.pwn"
//#include "zmeczenie/zmeczenie.pwn"
#include "sweeper/sweeper.pwn"
#include "fps/fps.pwn"
#include "magazynier/magazynier.pwn"
#include "03DL\03DL.pwn"
#include "actors\actors.pwn"
#include "admin\admin.pwn"
#include "adminduty\adminduty.pwn"
#include "animacje\animacje.pwn"
#include "antycheat\antycheat.pwn"
#include "antyspam\antyspam.pwn"
#include "biznesy\biznesy.pwn"
#include "bramy\bramy.pwn"
#include "bronie\bronie.pwn"
#include "budki\budki.pwn"
#include "bw\bw.pwn"
#include "chaty\chaty.pwn"
#include "choroby\choroby.pwn"
#include "convoy\convoy.pwn"
#include "cooking\cooking.pwn"
#include "drwal/drwal.pwn"
#include "debug\debug.pwn"
#include "discord\discord.pwn"
#include "fishing\fishing.pwn"
#include "frakcje\frakcje.pwn"
#include "glod\glod.pwn"
#include "gps\gps.pwn"
#include "graffiti\graffiti.pwn"
#include "ibiza\ibiza.pwn"
#include "komendy\komendy.pwn"
#include "logi\logi.pwn"
#include "money\money.pwn"
#include "motele\motele.pwn"
#include "szybyiauto/szybyiauto.pwn"
//#include "redscreen/redscreen.pwn"
//#include "mrpac\mrpac.pwn"
#include "names\names.pwn"
#include "napady\napady.pwn"
#include "napady\napad_domek.pwn"
#include "oferty\oferty.pwn"
#include "organizacje\organizacje.pwn"
#include "pizzaman\pizzaman.pwn"
#include "player_attachments\player_attachments.pwn"
#include "pojazdy\pojazdy.pwn"
#include "prace\prace.pwn"
#include "premium\premium.pwn"
#include "produkty\produkty.pwn"
#include "wejscia\wejscia.pwn"
#include "antycheat\antycheat.pwn"
#include "chaty\chaty.pwn"
#include "ibiza\ibiza.pwn"
#include "system-obiekty\system-obiekty.pwn"
#include "system-kary\system-kary.pwn"
#include "systemcial\systemcial.pwn"
#include "przedmioty\przedmioty.pwn"
#include "sannews\sannews.pwn"
#include "sila\sila.pwn"
#include "strzelnica\strzelnica.pwn"
#include "sklep\sklep.pwn"
#include "system-obiekty\system-obiekty.pwn"
#include "urzadls\urzadls.pwn"
#include "vehicle_attachments\vehicle_attachments.pwn"
#include "wejscia\wejscia.pwn"
#include "wypadek\wypadek.pwn"
#include "fotoradar/fotoradar.pwn"
#include "tune\tune.pwn"

//-------<[ timers ]>-------
#include "admin\admin_timers.pwn"
#include "antyspam\antyspam_timers.pwn"
#include "choroby\choroby_timers.pwn"
#include "convoy\convoy_timers.pwn"
#include "glod\glod_timers.pwn"
#include "gps\gps_timers.pwn"
#include "graffiti\graffiti_timers.pwn"
#include "money\money_timers.pwn"
//#include "mrpac\mrpac_timers.pwn"
#include "napady\napady_timers.pwn"
#include "organizacje\organizacje_timers.pwn"
#include "pojazdy\pojazdy_timers.pwn"
#include "prace\prace_timers.pwn"
#include "premium\premium_timers.pwn"
#include "sannews\sannews_timers.pwn"
#include "urzadls\urzadls_timers.pwn"
#include "wypadek\wypadek_timers.pwn"
#include "pojazdy\pojazdy_timers.pwn"
#include "strzelnica\strzelnica_timers.pwn"
#include "napady\napady_timers.pwn"
#include "przedmioty\przedmioty_timers.pwn"
#include "grupy\grupy_timers.pwn"


//-------<[ mysql ]>-------
#include "grupy\grupy_mysql.pwn"
#include "admin\admin_mysql.pwn"
#include "actors\actors_mysql.pwn"
#include "biznesy\biznesy_mysql.pwn"
#include "choroby\choroby_mysql.pwn"
#include "cooking\cooking_mysql.pwn"
#include "fishing\fishing_mysql.pwn"
#include "tatuaz\tatuaz_mysql.pwn"
#include "graffiti\graffiti_mysql.pwn"
#include "motele\motele_mysql.pwn"
#include "organizacje\organizacje_mysql.pwn"
#include "player_attachments\player_attachments_mysql.pwn"
#include "pojazdy\pojazdy_mysql.pwn"
#include "prace\prace_mysql.pwn"
#include "premium\premium_mysql.pwn"
#include "produkty\produkty_mysql.pwn"
#include "przedmioty\przedmioty_mysql.pwn"
#include "vehicle_attachments\vehicle_attachments_mysql.pwn"
#include "system-kary\system-kary_mysql.pwn"
#include "tune\tune_mysql.pwn"


//-------<[ others ]>-------
#include "03DL\resources.pwn"
#include "choroby\choroby_effects.pwn"
#include "przedmioty\przedmioty_telefon.pwn"


//-------<[ callbacks ]>-------
#include "grupy/grupy_callbacks.pwn"
#include "bilboard\bilboard_callbacks.pwn"
#include "gunshop/gunshop_callbacks.pwn"
#include "szmugler/szmugler_callbacks.pwn"
//#include "eventy/eventy_callbacks.pwn"
#include "deskorolka/deskorolka_callbacks.pwn"
#include "Nicki3D/Nicki3D_callbacks.pwn"
#include "tatuaz/tatuaz_callbacks.pwn"
//#include "zmeczenie/zmeczenie_callbacks.pwn"
#include "sweeper/sweeper_callbacks.pwn"
#include "fps/fps_callbacks.pwn"
#include "magazynier/magazynier_callbacks.pwn"
#include "admin\admin_callbacks.pwn"
#include "antycheat\antycheat_callbacks.pwn"
#include "biznesy\biznesy_callbacks.pwn"
#include "bramy\bramy_callbacks.pwn"
#include "choroby\choroby_callbacks.pwn"
#include "convoy\convoy_callbacks.pwn"
#include "cooking\cooking_callbacks.pwn"
#include "fishing\fishing_callbacks.pwn"
#include "glod\glod_callbacks.pwn"
#include "gps\gps_callbacks.pwn"
#include "logi\logi_callbacks.pwn"
#include "money\money_callbacks.pwn"
#include "motele\motele_callbacks.pwn"
//#include "mrpac\mrpac_callbacks.pwn"
#include "cooking\cooking_callbacks.pwn"
#include "antycheat\antycheat_callbacks.pwn"
#include "system-obiekty\system-obiekty_callbacks.pwn"
#include "przedmioty\przedmioty_callbacks.pwn"
#include "napady\napady_callbacks.pwn"
#include "organizacje\organizacje_callbacks.pwn"
#include "pizzaman\pizzaman_callbacks.pwn"
#include "player_attachments\player_attachments_callbacks.pwn"
#include "pojazdy\pojazdy_callbacks.pwn"
#include "prace\prace_callbacks.pwn"
#include "premium\premium_callbacks.pwn"
#include "produkty\produkty_callbacks.pwn"
#include "przedmioty\przedmioty_callbacks.pwn"
#include "strzelnica\strzelnica_callbacks.pwn"
#include "system-obiekty\system-obiekty_callbacks.pwn"
#include "vehicle_attachments\vehicle_attachments_callbacks.pwn"
#include "wypadek\wypadek_callbacks.pwn"
#include "tune\tune_callbacks.pwn"
#include "system-kary\system-kary_callbacks.pwn"


//-------<[ commands ]>-------
#include "grupy\commands\grupy_commands.pwn"
#include "wypadek\commands\wypadek_commands.pwn"
#include "bilboard\commands\bilboard_commands.pwn" 
#include "admin\commands\admin_commands.pwn"
#include "animacje\commands\animacje_commands.pwn"
#include "antycheat\commands\antycheat_commands.pwn"
#include "tatuaz\tatuaz_commands.pwn"
#include "biznesy\commands\biznesy_commands.pwn"
#include "bramy\commands\bramy_commands.pwn"
#include "chaty\commands\chaty_commands.pwn"
#include "choroby\commands\choroby_commands.pwn"
#include "convoy\commands\convoy_commands.pwn"
#include "cooking\commands\cooking_commands.pwn"
#include "debug\commands\debug_commands.pwn"
#include "fishing\commands\fishing_commands.pwn"
#include "frakcje\commands\frakcje_commands.pwn"
#include "glod\commands\glod_commands.pwn"
#include "gps\commands\gps_commands.pwn"
#include "graffiti\commands\graffiti_commands.pwn"
#include "ibiza\commands\ibiza_commands.pwn"
#include "komendy\commands\komendy_commands.pwn"
#include "logi\commands\logi_commands.pwn"
#include "motele\commands\motele_commands.pwn"
//#include "mrpac\commands\mrpac_commands.pwn"
#include "oferty\commands\oferty_commands.pwn"
#include "organizacje\commands\organizacje_commands.pwn"
#include "pizzaman\commands\pizzaman_commands.pwn"
#include "player_attachments\commands\player_attachments_commands.pwn"
#include "pojazdy\commands\pojazdy_commands.pwn"
#include "prace\commands\prace_commands.pwn"
#include "premium\commands\premium_commands.pwn"
#include "produkty\commands\produkty_commands.pwn"
#include "przedmioty\commands\przedmioty_commands.pwn"
#include "sannews\commands\sannews_commands.pwn"
#include "sila\commands\sila_commands.pwn"
#include "strzelnica\commands\strzelnica_commands.pwn"
#include "urzadls\commands\urzadls_commands.pwn"
#include "vehicle_attachments\commands\vehicle_attachments_commands.pwn"
#include "wypadek\commands\wypadek_commands.pwn"
#include "tune\commands\tune_commands.pwn"